// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CancelVKOperation():Promise<void>;

export function CheckIP():Promise<backend.IPInfo>;

export function CheckUpdate():Promise<backend.UpdateInfo>;

export function Connect(arg1:backend.ConnectParams):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GenerateReport(arg1:Array<backend.LogEntry>):Promise<string>;

export function GenerateVKHashes(arg1:number,arg2:Array<string>):Promise<Array<string>>;

export function GetAutoStart():Promise<boolean>;

export function GetObfsAccepted():Promise<boolean>;

export function GetObfsMode():Promise<string>;

export function GetProfile(arg1:string):Promise<backend.ProfileData>;

export function GetVersion():Promise<string>;

export function IsRunning():Promise<boolean>;

export function IsVKAuthAvailable():Promise<boolean>;

export function IsVKLoggedIn():Promise<boolean>;

export function ListProfiles():Promise<Record<string, backend.ProfileData>>;

export function MeasureLatency(arg1:string):Promise<number>;

export function SaveProfile(arg1:string,arg2:backend.ProfileData):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetObfsAccepted(arg1:boolean):Promise<void>;

export function SetObfsMode(arg1:string):Promise<void>;

export function VKLogin():Promise<void>;

export function VKLogout():Promise<void>;
