// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelVKOperation() {
  return window['go']['backend']['App']['CancelVKOperation']();
}

export function CheckIP() {
  return window['go']['backend']['App']['CheckIP']();
}

export function CheckUpdate() {
  return window['go']['backend']['App']['CheckUpdate']();
}

export function Connect(arg1) {
  return window['go']['backend']['App']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['backend']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['backend']['App']['Disconnect']();
}

export function GenerateReport(arg1) {
  return window['go']['backend']['App']['GenerateReport'](arg1);
}

export function GenerateVKHashes(arg1, arg2) {
  return window['go']['backend']['App']['GenerateVKHashes'](arg1, arg2);
}

export function GetAutoStart() {
  return window['go']['backend']['App']['GetAutoStart']();
}

export function GetObfsAccepted() {
  return window['go']['backend']['App']['GetObfsAccepted']();
}

export function GetObfsMode() {
  return window['go']['backend']['App']['GetObfsMode']();
}

export function GetProfile(arg1) {
  return window['go']['backend']['App']['GetProfile'](arg1);
}

export function GetVersion() {
  return window['go']['backend']['App']['GetVersion']();
}

export function IsRunning() {
  return window['go']['backend']['App']['IsRunning']();
}

export function IsVKAuthAvailable() {
  return window['go']['backend']['App']['IsVKAuthAvailable']();
}

export function IsVKLoggedIn() {
  return window['go']['backend']['App']['IsVKLoggedIn']();
}

export function ListProfiles() {
  return window['go']['backend']['App']['ListProfiles']();
}

export function MeasureLatency(arg1) {
  return window['go']['backend']['App']['MeasureLatency'](arg1);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['backend']['App']['SaveProfile'](arg1, arg2);
}

export function SetAutoStart(arg1) {
  return window['go']['backend']['App']['SetAutoStart'](arg1);
}

export function SetObfsAccepted(arg1) {
  return window['go']['backend']['App']['SetObfsAccepted'](arg1);
}

export function SetObfsMode(arg1) {
  return window['go']['backend']['App']['SetObfsMode'](arg1);
}

export function VKLogin() {
  return window['go']['backend']['App']['VKLogin']();
}

export function VKLogout() {
  return window['go']['backend']['App']['VKLogout']();
}
