// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddVKHash(arg1:string,arg2:string,arg3:string):Promise<backend.VKHashEntry>;

export function CheckAllVKHashes(arg1:string):Promise<Array<backend.VKHashCheckResult>>;

export function CheckVKHash(arg1:string,arg2:string):Promise<backend.VKHashCheckResult>;

export function CancelVKOperation():Promise<void>;

export function CancelVKHashChecks():Promise<void>;

export function CheckIP():Promise<backend.IPInfo>;

export function CheckUpdate():Promise<backend.UpdateInfo>;

export function Connect(arg1:backend.ConnectParams):Promise<void>;

export function DeleteVKHash(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GenerateReport(arg1:Array<backend.LogEntry>):Promise<string>;

export function GenerateVKHashes(arg1:number,arg2:Array<string>):Promise<Array<string>>;

export function GetAutoStart():Promise<boolean>;

export function GetDebugLogging():Promise<boolean>;

export function GetObfsAccepted():Promise<boolean>;

export function GetObfsMode():Promise<string>;

export function GetProfile(arg1:string):Promise<backend.ProfileData>;

export function GetVersion():Promise<string>;

export function IsRunning():Promise<boolean>;

export function IsVKAuthAvailable():Promise<boolean>;

export function IsVKLoggedIn():Promise<boolean>;

export function ListVKHashes():Promise<Array<backend.VKHashEntry>>;

export function ListProfiles():Promise<Record<string, backend.ProfileData>>;

export function MeasureLatency(arg1:string):Promise<number>;

export function ReplaceVKHash(arg1:string,arg2:string):Promise<backend.VKHashEntry>;

export function SaveProfile(arg1:string,arg2:backend.ProfileData):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetDebugLogging(arg1:boolean):Promise<void>;

export function SetObfsAccepted(arg1:boolean):Promise<void>;

export function SetObfsMode(arg1:string):Promise<void>;

export function SyncProfileVKSettings(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string,arg6:boolean,arg7:boolean):Promise<void>;

export function VKLogin():Promise<void>;

export function VKLogout():Promise<void>;
